swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login successful
          schema:
            $ref: '#/definitions/StandardResponse'
        '400':
          description: Invalid Fields
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup successful
          schema:
            $ref: '#/definitions/StandardResponse'
        '400':
          description: Invalid Fields
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'

  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/StandardResponse'
        '400':
          description: Invalid Fields
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'

    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/StandardResponse'
        '400':
          description: Invalid Fields
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'

  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get User Accounts
      description: API for fetching all bank accounts belonging to the authenticated user
      produces:
        - application/json
      responses:
        '200':
          description: User accounts retrieved successfully
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              message:
                type: string
                example: "User accounts retrieved successfully"
              data:
                type: array
                items:
                  $ref: '#/definitions/Account'
        '401':
          description: Unauthorized - Invalid or missing token
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'

  /account/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get monthly transactions by account
      description: Get all transactions for a specific account for the current month, filtered by user authentication
      parameters:
        - in: path
          name: accountId
          type: string
          required: true
          description: ID of the bank account
        - in: query
          name: month
          type: string
          format: date
          description: Month to get transactions for (YYYY-MM format). Defaults to current month if not specified
          required: false 
      produces:
        - application/json
      responses:
        '200':
          description: Account transactions retrieved successfully
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              message:
                type: string
                example: "Transactions retrieved successfully"
              data:
                type: object
                properties:
                  accountId:
                    type: string
                  accountName:
                    type: string
                  currentBalance:
                    type: number
                  transactions:
                    type: array
                    items:
                      $ref: '#/definitions/Transaction'
        '400':
          description: Invalid account ID or date format
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Forbidden - Account does not belong to authenticated user
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: Account not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'

  /account/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get specific transaction details
      description: Get detailed information about a specific transaction for a specific account, with user authentication verification
      parameters:
        - in: path
          name: accountId
          type: string
          required: true
          description: ID of the bank account
        - in: path
          name: transactionId
          type: string
          required: true
          description: ID of the transaction
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              message:
                type: string
                example: "Transaction details retrieved successfully"
              data:
                $ref: '#/definitions/TransactionDetail'
        '400':
          description: Invalid account ID or transaction ID
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Forbidden - Account or transaction does not belong to authenticated user
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: Transaction or account not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'

    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction details
      description: Update categorie & notes
      parameters:
        - in: path
          name: accountId
          type: string
          required: true
          description: ID of the bank account
        - in: path
          name: transactionId
          type: string
          required: true
          description: ID of the transaction
        - in: body
          name: body
          description: Transaction update payload
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              message:
                type: string
                example: "Transaction updated successfully"
              data:
                $ref: '#/definitions/TransactionDetail'
        '400':
          description: Invalid account ID, transaction ID, or update data
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Forbidden - Account or transaction does not belong to authenticated user
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: Transaction or account not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
      password:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      userName:
        type: string

  Login:
    properties:
      email:
        type: string
      password:
        type: string

  UserProfile:
    type: object
    properties:
      userName:
        type: string

  TransactionUpdate:
    type: object
    properties:
      title:
        type: string
      category:
        type: string
        enum: [Food, Transport, Shopping, Entertainment, Bills, Health, Other]
      notes:
        type: string

  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date-time
      title:
        type: string
      amount:
        type: number
      balance:
        type: number
      type:
        type: string
        enum: [En ligne, Retrait distributeur, Virement, Paiement]
      category:
        type: string
        enum: [Food, Transport, Shopping, Entertainment, Bills, Health, Other]
      notes:
        type: string

  TransactionDetail:
    type: object
    properties:
      id:
        type: string
        description: Unique transaction identifier
      accountId:
        type: string
        description: Account ID this transaction belongs to
      date:
        type: string
        format: date-time
        description: Transaction date and time
      title:
        type: string
        description: Transaction title/description
      amount:
        type: number
        description: Transaction amount (positive for credits, negative for debits)
      balance:
        type: number
        description: Account balance after this transaction
      type:
        type: string
        enum: [En ligne, Retrait distributeur, Virement, Paiement]
        description: Type of transaction
      category:
        type: string
        enum: [Food, Transport, Shopping, Entertainment, Bills, Health, Other]
        description: Transaction category
      notes:
        type: string
        description: Additional notes about the transaction
      merchant:
        type: string
        description: Merchant or counterpart information
      location:
        type: string
        description: Transaction location if available
      createdAt:
        type: string
        format: date-time
        description: When the transaction record was created
      updatedAt:
        type: string
        format: date-time
        description: When the transaction record was last updated

  AccountTransactions:
    type: object
    properties:
      accountId:
        type: string
        description: Unique account identifier
      accountName:
        type: string
        description: Display name of the account
      accountType:
        type: string
        enum: [Checking, Savings, Credit Card]
        description: Type of bank account
      currentBalance:
        type: number
        description: Current account balance
      currency:
        type: string
        default: EUR
        description: Account currency
      month:
        type: string
        format: date
        description: Month for which transactions are retrieved (YYYY-MM)
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'
        description: List of transactions for the specified period

  StandardResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      data:
        type: object

  ErrorResponse:
    type: object
    properties:
      status:
        type: integer
      error:
        type: string
      message:
        type: string

  Account:
    type: object
    properties:
      id:
        type: string
        description: Unique account identifier
      userId:
        type: string
        description: ID of the user who owns this account
      accountNumber:
        type: string
        description: Bank account number
      accountName:
        type: string
        description: Display name of the account
      accountType:
        type: string
        enum: [Checking, Savings, Credit Card]
        description: Type of bank account
      balance:
        type: number
        description: Current account balance
      currency:
        type: string
        default: EUR
        description: Account currency
      isActive:
        type: boolean
        default: true
        description: Whether the account is active
      createdAt:
        type: string
        format: date-time
        description: When the account was created
      updatedAt:
        type: string
        format: date-time
        description: When the account was last updated
